#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mox3
Version  : 1.0.0
Release  : 42
URL      : https://files.pythonhosted.org/packages/93/28/29e5ab31e3a5614ebb2e48be699e921081ff167b8d3ac2b3a63d1accecc1/mox3-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/93/28/29e5ab31e3a5614ebb2e48be699e921081ff167b8d3ac2b3a63d1accecc1/mox3-1.0.0.tar.gz
Summary  : Mock object framework for Python
Group    : Development/Tools
License  : Apache-2.0
Requires: mox3-license = %{version}-%{release}
Requires: mox3-python = %{version}-%{release}
Requires: mox3-python3 = %{version}-%{release}
Requires: fixtures
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : fixtures
BuildRequires : pbr

%description
=========================================
Mox3 - Mock object framework for Python 3
=========================================

.. image:: https://governance.openstack.org/tc/badges/mox3.svg
    :target: https://governance.openstack.org/tc/reference/tags/index.html

Mox3 is an unofficial port of the Google mox framework
(http://code.google.com/p/pymox/) to Python 3. It was meant to be as compatible
with mox as possible, but small enhancements have been made. The library was
tested on Python version 3.2, 2.7 and 2.6.

Use at your own risk ;)

To install:

  $ python setup.py install

Running Tests
-------------
The testing system is based on a combination of tox and testr. The canonical
approach to running tests is to simply run the command `tox`. This will
create virtual environments, populate them with depenedencies and run all of
the tests that OpenStack CI systems run. Behind the scenes, tox is running
`testr run --parallel`, but is set up such that you can supply any additional
testr arguments that are needed to tox. For example, you can run:
`tox -- --analyze-isolation` to cause tox to tell testr to add
--analyze-isolation to its argument list.

It is also possible to run the tests inside of a virtual environment
you have created, or it is possible that you have all of the dependencies
installed locally already. In this case, you can interact with the testr
command directly. Running `testr run` will run the entire test suite. `testr
run --parallel` will run it in parallel (this is the default incantation tox
uses.) More information about testr can be found at:
https://wiki.openstack.org/wiki/Testr

Basic Usage
-----------

The basic usage of mox3 is the same as with mox, but the initial import should
be made from the mox3 module:

  from mox3 import mox

To learn how to use mox3 you may check the documentation of the original mox
framework:

  http://code.google.com/p/pymox/wiki/MoxDocumentation

Original Copyright
------------------

Mox is Copyright 2008 Google Inc, and licensed under the Apache
License, Version 2.0; see the file COPYING.txt for details.  If you would
like to help us improve Mox, join the group.

OpenStack Fork
--------------

* Free software: Apache license
* Documentation: https://docs.openstack.org/mox3/latest/
* Source: https://opendev.org/openstack/mox3
* Bugs: https://bugs.launchpad.net/python-mox3

%package license
Summary: license components for the mox3 package.
Group: Default

%description license
license components for the mox3 package.


%package python
Summary: python components for the mox3 package.
Group: Default
Requires: mox3-python3 = %{version}-%{release}

%description python
python components for the mox3 package.


%package python3
Summary: python3 components for the mox3 package.
Group: Default
Requires: python3-core
Provides: pypi(mox3)

%description python3
python3 components for the mox3 package.


%prep
%setup -q -n mox3-1.0.0
cd %{_builddir}/mox3-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583174300
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mox3
cp %{_builddir}/mox3-1.0.0/COPYING.txt %{buildroot}/usr/share/package-licenses/mox3/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mox3/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
