#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mox3
Version  : 1.1.0
Release  : 43
URL      : https://files.pythonhosted.org/packages/90/ac/2220e111a63e32872567d6e677b4b36163c0c5ac766ef76d00dee3eabdf9/mox3-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/90/ac/2220e111a63e32872567d6e677b4b36163c0c5ac766ef76d00dee3eabdf9/mox3-1.1.0.tar.gz
Summary  : Mock object framework for Python
Group    : Development/Tools
License  : Apache-2.0
Requires: mox3-license = %{version}-%{release}
Requires: mox3-python = %{version}-%{release}
Requires: mox3-python3 = %{version}-%{release}
Requires: fixtures
Requires: pbr
BuildRequires : buildreq-distutils3
BuildRequires : fixtures
BuildRequires : pbr

%description
Mox3 - Mock object framework for Python 3
        =========================================

%package license
Summary: license components for the mox3 package.
Group: Default

%description license
license components for the mox3 package.


%package python
Summary: python components for the mox3 package.
Group: Default
Requires: mox3-python3 = %{version}-%{release}

%description python
python components for the mox3 package.


%package python3
Summary: python3 components for the mox3 package.
Group: Default
Requires: python3-core
Provides: pypi(mox3)
Requires: pypi(fixtures)
Requires: pypi(pbr)

%description python3
python3 components for the mox3 package.


%prep
%setup -q -n mox3-1.1.0
cd %{_builddir}/mox3-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1591283730
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mox3
cp %{_builddir}/mox3-1.1.0/COPYING.txt %{buildroot}/usr/share/package-licenses/mox3/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mox3/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
